#!/bin/bash -e

# SPDX-FileCopyrightText: 2025 David Campbell <david@hnefatafl.org>
# SPDX-License-Identifier: MIT

export RUSTFLAGS='-D warnings'

cargo fmt --all --check
cargo clippy --all-targets --all-features --keep-going
cargo test --all-targets --all-features

# cargo install zizmor --locked
zizmor --pedantic .github/

# sudo apt-get install reuse
reuse lint
