#!/bin/bash -e

# SPDX-FileCopyrightText: 2025 David Campbell <david@hnefatafl.or>
# SPDX-License-Identifier: MIT

export RUSTFLAGS='-D warnings'

cargo fmt --all --check
cargo clippy --all-targets --examples
cargo test
cargo test --benches

# cargo install zizmor --locked
zizmor --pedantic .github/

# sudo apt-get install reuse
# reuse lint
