[book]
title = "Copenhagen Hnefatafl"
description = """
Join a friendly community and play Copenhagen Hnefatafl. Figure out how to \
install the software, play by the rules, chat on Discord, find Help, and Donate."""
authors = [
    "David Lawrence Campbell",
]
language = "en"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/dcampbell24/hnefatafl"
mathjax-support = true
input-404 = "404.md"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.djot]
