[book]
title = "Copenhagen Hnefatafl 0.13.2"
description = "Join a friendly community and play Copenhagen Hnefatafl"
authors = [
    "David Lawrence Campbell",
]
language = "en"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/dcampbell24/hnefatafl-copenhagen"
mathjax-support = true
input-404 = "404.md"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.djot]
