on: push
name: All of the Rust Commit Checks

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-D warnings"

permissions:
  actions: read # An explanation.

jobs:
  clippy_check:
    name: clippy check
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    permissions:
      security-events: write # An explanation.
      actions: read # An explanation.

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v5
        with:
          persist-credentials: false

      - name: Run clippy
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev mold

          rustup component add clippy rustfmt
          rustup update stable

          cargo fmt --all --check
          cargo clippy --examples
          cargo test
          cargo test --benches
